@file:Suppress(
    "unused"
)

package crosstech.aviaassist.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4459A9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001452)
val md_theme_light_secondary = Color(0xFF5A5D72)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE1F9)
val md_theme_light_onSecondaryContainer = Color(0xFF171B2C)
val md_theme_light_tertiary = Color(0xFF984060)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onTertiaryContainer = Color(0xFF3E001D)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFEFBFF)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
val md_theme_light_outline = Color(0xFF767680)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB7C4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4459A9)
val md_theme_light_outlineVariant = Color(0xFFC6C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB7C4FF)
val md_theme_dark_onPrimary = Color(0xFF0E2878)
val md_theme_dark_primaryContainer = Color(0xFF2B4090)
val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_secondary = Color(0xFFC2C5DD)
val md_theme_dark_onSecondary = Color(0xFF2C2F42)
val md_theme_dark_secondaryContainer = Color(0xFF424659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1F9)
val md_theme_dark_tertiary = Color(0xFFFFB1C8)
val md_theme_dark_onTertiary = Color(0xFF5E1132)
val md_theme_dark_tertiaryContainer = Color(0xFF7B2949)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E1E6)
val md_theme_dark_surface = Color(0xFF1B1B1F)
val md_theme_dark_onSurface = Color(0xFFE4E1E6)
val md_theme_dark_surfaceVariant = Color(0xFF45464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
val md_theme_dark_outline = Color(0xFF90909A)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
val md_theme_dark_inversePrimary = Color(0xFF4459A9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB7C4FF)
val md_theme_dark_outlineVariant = Color(0xFF45464F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFACBBFF)
val CustomColor1 = Color(0xFF13ABCE)
val CustomColor2 = Color(0xFF18FE8D)
val CustomColor3 = Color(0xFF28DCAE)
val light_CustomColor1 = Color(0xFF00677E)
val light_onCustomColor1 = Color(0xFFFFFFFF)
val light_CustomColor1Container = Color(0xFFB4EBFF)
val light_onCustomColor1Container = Color(0xFF001F28)
val dark_CustomColor1 = Color(0xFF59D5FA)
val dark_onCustomColor1 = Color(0xFF003542)
val dark_CustomColor1Container = Color(0xFF004E5F)
val dark_onCustomColor1Container = Color(0xFFB4EBFF)
val light_CustomColor2 = Color(0xFF006D38)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFF5EFF9C)
val light_onCustomColor2Container = Color(0xFF00210D)
val dark_CustomColor2 = Color(0xFF00E47C)
val dark_onCustomColor2 = Color(0xFF00391B)
val dark_CustomColor2Container = Color(0xFF005229)
val dark_onCustomColor2Container = Color(0xFF5EFF9C)
val light_CustomColor3 = Color(0xFF006C53)
val light_onCustomColor3 = Color(0xFFFFFFFF)
val light_CustomColor3Container = Color(0xFF59FCCC)
val light_onCustomColor3Container = Color(0xFF002117)
val dark_CustomColor3 = Color(0xFF2EDFB1)
val dark_onCustomColor3 = Color(0xFF00382A)
val dark_CustomColor3Container = Color(0xFF00513E)
val dark_onCustomColor3Container = Color(0xFF59FCCC)